services:
  db:
    image: mariadb:10.5
    # restart: unless-stopped
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ns81_data:/var/lib/mysql
      - ../..:/workspaces:cached
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: ns81
      MYSQL_USER: user
      MYSQL_PASSWORD: naisyo

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  ns81_data:
